{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c9921755-7a07-41fa-b50f-c70ae082eda7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ File saved!\n",
      "🚀 Launching...\n",
      "\n",
      "  You can now view your Streamlit app in your browser.\n",
      "\n",
      "  Local URL: http://localhost:8502\n",
      "  Network URL: http://128.189.28.206:8502\n",
      "\n",
      "  For better performance, install the Watchdog module:\n",
      "\n",
      "  $ xcode-select --install\n",
      "  $ pip install watchdog\n",
      "            \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-04-15 14:54:34.048 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n"
     ]
    }
   ],
   "source": [
    "code = '''\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from collections import defaultdict\n",
    "from io import BytesIO\n",
    "import xlsxwriter\n",
    "\n",
    "st.set_page_config(page_title=\"ProjectPERT\", page_icon=\"📊\", layout=\"wide\")\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "@import url(\\'https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;500;600&display=swap\\');\n",
    "html, body, [class*=\"css\"] { font-family: \\'DM Sans\\', sans-serif; font-size: 22px; }\n",
    ".stApp { background-color: #f0f2f8; color: #1a1a2e; }\n",
    "#MainMenu, footer, header { visibility: hidden; }\n",
    ".hero { background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); border-radius: 16px; padding: 2.5rem 3rem; margin-bottom: 2rem; }\n",
    ".hero-title { font-family: \\'Space Mono\\', monospace; font-size: 3.2rem; font-weight: 700; color: #ffffff; margin: 0 0 0.4rem 0; }\n",
    ".hero-sub { color: rgba(255,255,255,0.75); font-size: 1.4rem; margin: 0; }\n",
    ".card { background: #ffffff; border: 1px solid #dde1f0; border-radius: 12px; padding: 1.8rem; margin-bottom: 1.2rem; box-shadow: 0 2px 8px rgba(99,102,241,0.07); }\n",
    ".section-label { font-family: \\'Space Mono\\', monospace; font-size: 0.95rem; letter-spacing: 3px; text-transform: uppercase; color: #6366f1; margin-bottom: 1rem; }\n",
    ".metric-row { display: flex; gap: 1rem; margin-bottom: 1.5rem; }\n",
    ".metric-tile { flex: 1; background: #ffffff; border: 1px solid #dde1f0; border-radius: 10px; padding: 1.6rem; text-align: center; box-shadow: 0 2px 8px rgba(99,102,241,0.07); }\n",
    ".metric-val { font-family: \\'Space Mono\\', monospace; font-size: 2.8rem; font-weight: 700; color: #4f46e5; }\n",
    ".metric-lbl { font-size: 1.1rem; color: #888; margin-top: 0.4rem; }\n",
    ".stButton>button { background: linear-gradient(135deg, #4f46e5, #7c3aed); color: white; border: none; border-radius: 8px; padding: 0.85rem 2rem; font-family: \\'Space Mono\\', monospace; font-size: 1.1rem; }\n",
    ".stButton>button:hover { opacity: 0.88; }\n",
    "label, .stTextInput label, .stNumberInput label, .stSlider label, .stSelectbox label, .stMultiSelect label { color: #333 !important; font-size: 1.15rem !important; font-weight: 500 !important; }\n",
    "div[data-testid=\"stNumberInput\"] input, div[data-testid=\"stTextInput\"] input { font-size: 1.1rem !important; padding: 0.6rem !important; }\n",
    "p, li { font-size: 1.1rem; line-height: 1.8; }\n",
    "hr { border-color: #dde1f0; }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "UNIT_OPTIONS = [\"Minutes\", \"Hours\", \"Days\", \"Weeks\", \"Months\", \"Years\"]\n",
    "\n",
    "def pert_mean(a, m, b): return (a + 4*m + b) / 6\n",
    "def pert_std(a, b): return (b - a) / 6\n",
    "\n",
    "def topological_sort(activities):\n",
    "    in_degree = {act: 0 for act in activities}\n",
    "    adj = defaultdict(list)\n",
    "    for act, info in activities.items():\n",
    "        for pred in info[\"predecessors\"]:\n",
    "            adj[pred].append(act)\n",
    "            in_degree[act] += 1\n",
    "    queue = [a for a in activities if in_degree[a] == 0]\n",
    "    order = []\n",
    "    while queue:\n",
    "        node = queue.pop(0)\n",
    "        order.append(node)\n",
    "        for neighbor in adj[node]:\n",
    "            in_degree[neighbor] -= 1\n",
    "            if in_degree[neighbor] == 0:\n",
    "                queue.append(neighbor)\n",
    "    return order\n",
    "\n",
    "def simulate_project(activities, n_simulations=10_000):\n",
    "    order = topological_sort(activities)\n",
    "    project_durations = []\n",
    "    for _ in range(n_simulations):\n",
    "        finish = {}\n",
    "        for act in order:\n",
    "            a, m, b = activities[act][\"min\"], activities[act][\"avg\"], activities[act][\"max\"]\n",
    "            duration = np.random.triangular(a, m, b)\n",
    "            preds = activities[act][\"predecessors\"]\n",
    "            start = max((finish[p] for p in preds), default=0)\n",
    "            finish[act] = start + duration\n",
    "        project_durations.append(max(finish.values()))\n",
    "    return np.array(project_durations)\n",
    "\n",
    "def compute_pert_critical_path(activities):\n",
    "    order = topological_sort(activities)\n",
    "    exp_dur = {a: pert_mean(activities[a][\"min\"], activities[a][\"avg\"], activities[a][\"max\"]) for a in activities}\n",
    "    earliest_finish = {}\n",
    "    for act in order:\n",
    "        preds = activities[act][\"predecessors\"]\n",
    "        start = max((earliest_finish[p] for p in preds), default=0)\n",
    "        earliest_finish[act] = start + exp_dur[act]\n",
    "    end_node = max(earliest_finish, key=earliest_finish.get)\n",
    "    def backtrack(node):\n",
    "        preds = activities[node][\"predecessors\"]\n",
    "        if not preds: return [node]\n",
    "        return backtrack(max(preds, key=lambda p: earliest_finish[p])) + [node]\n",
    "    return max(earliest_finish.values()), backtrack(end_node), exp_dur, earliest_finish\n",
    "\n",
    "def export_to_excel(activities, durations, pert_dur, crit_path, sl, unit):\n",
    "    output = BytesIO()\n",
    "    mean_dur = float(np.mean(durations))\n",
    "    std_dur  = float(np.std(durations))\n",
    "    sl_val   = float(np.percentile(durations, sl))\n",
    "\n",
    "    wb = xlsxwriter.Workbook(output, {\"in_memory\": True})\n",
    "\n",
    "    title_fmt  = wb.add_format({\"bold\": True, \"font_size\": 16, \"font_color\": \"#4f46e5\", \"bottom\": 2, \"bottom_color\": \"#4f46e5\"})\n",
    "    hdr_fmt    = wb.add_format({\"bold\": True, \"bg_color\": \"#4f46e5\", \"font_color\": \"#ffffff\", \"font_size\": 12, \"border\": 1, \"align\": \"center\"})\n",
    "    cell_fmt   = wb.add_format({\"font_size\": 11, \"border\": 1, \"border_color\": \"#dde1f0\"})\n",
    "    num_fmt    = wb.add_format({\"font_size\": 11, \"border\": 1, \"border_color\": \"#dde1f0\", \"num_format\": \"0.00\", \"align\": \"center\"})\n",
    "    hi_fmt     = wb.add_format({\"font_size\": 11, \"border\": 1, \"bg_color\": \"#fef2f2\", \"font_color\": \"#dc2626\", \"bold\": True})\n",
    "    ml_fmt     = wb.add_format({\"bold\": True, \"font_size\": 12, \"bg_color\": \"#eef2ff\", \"border\": 1})\n",
    "    mv_fmt     = wb.add_format({\"font_size\": 12, \"border\": 1, \"num_format\": \"0.00\", \"font_color\": \"#4f46e5\", \"bold\": True})\n",
    "    red_fmt    = wb.add_format({\"font_size\": 11, \"border\": 1, \"font_color\": \"#dc2626\", \"bold\": True})\n",
    "\n",
    "    # Sheet 1: Summary\n",
    "    ws1 = wb.add_worksheet(\"Summary\")\n",
    "    ws1.set_column(\"A:A\", 34); ws1.set_column(\"B:B\", 22)\n",
    "    ws1.write(\"A1\", \"ProjectPERT — Simulation Summary\", title_fmt)\n",
    "    ws1.write(\"A2\", f\"Time unit: {unit}\")\n",
    "    for i, (lbl, val) in enumerate([\n",
    "        (\"Mean Project Duration\", mean_dur),\n",
    "        (\"Std Deviation\", std_dur),\n",
    "        (f\"{sl}% Service Level Duration\", sl_val),\n",
    "        (\"PERT Expected Duration\", pert_dur),\n",
    "    ], start=3):\n",
    "        ws1.write(i, 0, lbl, ml_fmt)\n",
    "        ws1.write(i, 1, val, mv_fmt)\n",
    "    ws1.write(7, 0, \"Critical Path\", ml_fmt)\n",
    "    ws1.write(7, 1, \" > \".join(crit_path), red_fmt)\n",
    "\n",
    "    # Sheet 2: Activities\n",
    "    ws2 = wb.add_worksheet(\"Activities\")\n",
    "    ws2.set_column(\"A:A\", 8); ws2.set_column(\"B:B\", 28); ws2.set_column(\"C:C\", 22); ws2.set_column(\"D:I\", 14)\n",
    "    for col, h in enumerate([\"Label\",\"Activity\",\"Predecessors\",f\"Min ({unit})\",f\"Avg ({unit})\",f\"Max ({unit})\",\"PERT Mean\",\"Std Dev\",\"Critical\"]):\n",
    "        ws2.write(0, col, h, hdr_fmt)\n",
    "    for row, (lbl, info) in enumerate(activities.items(), start=1):\n",
    "        mu  = pert_mean(info[\"min\"], info[\"avg\"], info[\"max\"])\n",
    "        sig = pert_std(info[\"min\"], info[\"max\"])\n",
    "        fmt = hi_fmt if lbl in crit_path else cell_fmt\n",
    "        ws2.write(row, 0, lbl, fmt)\n",
    "        ws2.write(row, 1, info[\"name\"], fmt)\n",
    "        ws2.write(row, 2, \", \".join(info[\"predecessors\"]) or \"-\", fmt)\n",
    "        ws2.write(row, 3, info[\"min\"], num_fmt)\n",
    "        ws2.write(row, 4, info[\"avg\"], num_fmt)\n",
    "        ws2.write(row, 5, info[\"max\"], num_fmt)\n",
    "        ws2.write(row, 6, round(mu, 2), num_fmt)\n",
    "        ws2.write(row, 7, round(sig, 2), num_fmt)\n",
    "        ws2.write(row, 8, \"YES\" if lbl in crit_path else \"\", fmt)\n",
    "\n",
    "    # Sheet 3: Simulation Data (capped at 5000 rows)\n",
    "    ws3 = wb.add_worksheet(\"Simulation Data\")\n",
    "    ws3.set_column(\"A:B\", 20)\n",
    "    ws3.write(0, 0, \"Simulation #\", hdr_fmt)\n",
    "    ws3.write(0, 1, f\"Duration ({unit})\", hdr_fmt)\n",
    "    for i, val in enumerate(durations[:5000], start=1):\n",
    "        ws3.write(i, 0, i, cell_fmt)\n",
    "        ws3.write(i, 1, round(float(val), 4), num_fmt)\n",
    "\n",
    "    # Sheet 4: Histogram with chart\n",
    "    ws4 = wb.add_worksheet(\"Histogram\")\n",
    "    ws4.set_column(\"A:B\", 22)\n",
    "    ws4.write(0, 0, f\"Duration Bin ({unit})\", hdr_fmt)\n",
    "    ws4.write(0, 1, \"Frequency\", hdr_fmt)\n",
    "    counts, bin_edges = np.histogram(durations, bins=40)\n",
    "    for i, (count, edge) in enumerate(zip(counts, bin_edges), start=1):\n",
    "        ws4.write(i, 0, round(float(edge), 2), num_fmt)\n",
    "        ws4.write(i, 1, int(count), cell_fmt)\n",
    "    chart = wb.add_chart({\"type\": \"column\"})\n",
    "    chart.add_series({\n",
    "        \"name\": \"Frequency\",\n",
    "        \"categories\": [\"Histogram\", 1, 0, len(counts), 0],\n",
    "        \"values\":     [\"Histogram\", 1, 1, len(counts), 1],\n",
    "        \"fill\": {\"color\": \"#6366f1\"}, \"border\": {\"color\": \"#ffffff\"},\n",
    "    })\n",
    "    chart.set_title({\"name\": \"Project Duration Distribution\"})\n",
    "    chart.set_x_axis({\"name\": f\"Duration ({unit})\"})\n",
    "    chart.set_y_axis({\"name\": \"Frequency\"})\n",
    "    chart.set_style(10)\n",
    "    ws4.insert_chart(\"D2\", chart, {\"x_scale\": 1.8, \"y_scale\": 1.5})\n",
    "\n",
    "    wb.close()\n",
    "    output.seek(0)\n",
    "    return output\n",
    "\n",
    "# Session state\n",
    "if \"activities\" not in st.session_state:\n",
    "    st.session_state.activities = {\n",
    "        \"A\": {\"name\": \"Design\",                \"predecessors\": [],        \"min\": 16, \"avg\": 21, \"max\": 26},\n",
    "        \"B\": {\"name\": \"Build prototype\",       \"predecessors\": [\"A\"],     \"min\": 3,  \"avg\": 6,  \"max\": 9},\n",
    "        \"C\": {\"name\": \"Evaluate equipment\",    \"predecessors\": [\"A\"],     \"min\": 5,  \"avg\": 7,  \"max\": 9},\n",
    "        \"D\": {\"name\": \"Test prototype\",        \"predecessors\": [\"B\"],     \"min\": 2,  \"avg\": 3,  \"max\": 4},\n",
    "        \"E\": {\"name\": \"Write equipment report\",\"predecessors\": [\"C\",\"D\"], \"min\": 4,  \"avg\": 6,  \"max\": 8},\n",
    "        \"F\": {\"name\": \"Write methods report\",  \"predecessors\": [\"C\",\"D\"], \"min\": 6,  \"avg\": 8,  \"max\": 10},\n",
    "        \"G\": {\"name\": \"Write final report\",    \"predecessors\": [\"E\",\"F\"], \"min\": 1,  \"avg\": 2,  \"max\": 3},\n",
    "    }\n",
    "if \"results\"   not in st.session_state: st.session_state.results   = None\n",
    "if \"time_unit\" not in st.session_state: st.session_state.time_unit = \"Weeks\"\n",
    "\n",
    "# Hero\n",
    "st.markdown(\\'\\'\\'<div class=\"hero\">\n",
    "  <div class=\"hero-title\">ProjectPERT</div>\n",
    "  <p class=\"hero-sub\">Monte Carlo · Critical Path · Duration Forecaster</p>\n",
    "</div>\\'\\'\\', unsafe_allow_html=True)\n",
    "\n",
    "left_col, right_col = st.columns([1.1, 1.9], gap=\"large\")\n",
    "\n",
    "with left_col:\n",
    "    st.markdown(\\'<div class=\"section-label\">Activity Network</div>\\', unsafe_allow_html=True)\n",
    "    time_unit = st.selectbox(\"Time Unit\", UNIT_OPTIONS, index=UNIT_OPTIONS.index(st.session_state.time_unit))\n",
    "    st.session_state.time_unit = time_unit\n",
    "    acts = st.session_state.activities\n",
    "    rows = [{\"Label\": l, \"Activity\": i[\"name\"], \"Predecessors\": \", \".join(i[\"predecessors\"]) or \"-\",\n",
    "             f\"Min ({time_unit})\": i[\"min\"], f\"Avg ({time_unit})\": i[\"avg\"], f\"Max ({time_unit})\": i[\"max\"]}\n",
    "            for l, i in acts.items()]\n",
    "    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    with st.expander(\"Add / Edit an Activity\"):\n",
    "        existing_labels = list(acts.keys())\n",
    "        new_label = st.text_input(\"Label (e.g. H)\", max_chars=5, placeholder=\"H\").strip().upper()\n",
    "        new_name  = st.text_input(\"Activity name\", placeholder=\"e.g. User testing\")\n",
    "        selected_preds = st.multiselect(\"Immediate predecessors\", options=[l for l in existing_labels if l != new_label])\n",
    "        c1, c2, c3 = st.columns(3)\n",
    "        with c1: new_min = st.number_input(f\"Min ({time_unit})\", min_value=0, value=1)\n",
    "        with c2: new_avg = st.number_input(f\"Avg ({time_unit})\", min_value=0, value=3)\n",
    "        with c3: new_max = st.number_input(f\"Max ({time_unit})\", min_value=0, value=5)\n",
    "        if st.button(\"Save Activity\"):\n",
    "            if not new_label: st.error(\"Please enter a label.\")\n",
    "            elif new_min > new_avg or new_avg > new_max: st.error(\"Need: Min <= Avg <= Max\")\n",
    "            elif not new_name: st.error(\"Please enter an activity name.\")\n",
    "            else:\n",
    "                st.session_state.activities[new_label] = {\"name\": new_name, \"predecessors\": selected_preds, \"min\": new_min, \"avg\": new_avg, \"max\": new_max}\n",
    "                st.session_state.results = None\n",
    "                st.rerun()\n",
    "\n",
    "    with st.expander(\"Remove an Activity\"):\n",
    "        to_remove = st.selectbox(\"Select activity to remove\", options=[\"--\"] + list(acts.keys()))\n",
    "        if st.button(\"Remove\") and to_remove != \"--\":\n",
    "            del st.session_state.activities[to_remove]\n",
    "            for a in st.session_state.activities:\n",
    "                st.session_state.activities[a][\"predecessors\"] = [p for p in st.session_state.activities[a][\"predecessors\"] if p != to_remove]\n",
    "            st.session_state.results = None\n",
    "            st.rerun()\n",
    "\n",
    "    if st.button(\"Reset to Example Project\"):\n",
    "        del st.session_state[\"activities\"]\n",
    "        st.session_state.results = None\n",
    "        st.rerun()\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\\'<div class=\"section-label\">Simulation Settings</div>\\', unsafe_allow_html=True)\n",
    "    n_sim = st.select_slider(\"Monte Carlo iterations\", options=[1_000, 5_000, 10_000, 50_000, 100_000], value=10_000, format_func=lambda x: f\"{x:,}\")\n",
    "    service_level = st.slider(\"Service level (%)\", min_value=50, max_value=99, value=95, step=1)\n",
    "    run_btn = st.button(\"Run Simulation\", use_container_width=True)\n",
    "\n",
    "with right_col:\n",
    "    if run_btn:\n",
    "        with st.spinner(\"Running simulation...\"):\n",
    "            durations = simulate_project(st.session_state.activities, n_simulations=n_sim)\n",
    "            pert_dur, crit_path, exp_durs, ef = compute_pert_critical_path(st.session_state.activities)\n",
    "            st.session_state.results = {\"durations\": durations, \"pert_dur\": pert_dur, \"crit_path\": crit_path, \"service_level\": service_level}\n",
    "\n",
    "    if st.session_state.results:\n",
    "        res      = st.session_state.results\n",
    "        durations = res[\"durations\"]\n",
    "        sl        = res[\"service_level\"]\n",
    "        unit      = st.session_state.time_unit\n",
    "        mean_dur  = np.mean(durations)\n",
    "        std_dur   = np.std(durations)\n",
    "        sl_val    = np.percentile(durations, sl)\n",
    "\n",
    "        st.markdown(\\'<div class=\"section-label\">Forecast Results</div>\\', unsafe_allow_html=True)\n",
    "        st.markdown(f\\'\\'\\'<div class=\"metric-row\">\n",
    "          <div class=\"metric-tile\"><div class=\"metric-val\">{mean_dur:.1f}</div><div class=\"metric-lbl\">Mean Duration ({unit})</div></div>\n",
    "          <div class=\"metric-tile\"><div class=\"metric-val\">{std_dur:.1f}</div><div class=\"metric-lbl\">Std Deviation</div></div>\n",
    "          <div class=\"metric-tile\"><div class=\"metric-val\">{sl_val:.1f}</div><div class=\"metric-lbl\">{sl}% Service Level ({unit})</div></div>\n",
    "          <div class=\"metric-tile\"><div class=\"metric-val\">{res[\"pert_dur\"]:.1f}</div><div class=\"metric-lbl\">PERT Expected ({unit})</div></div>\n",
    "        </div>\\'\\'\\', unsafe_allow_html=True)\n",
    "\n",
    "        acts_ref = st.session_state.activities\n",
    "        path_str = \" > \".join(f\"{l} ({acts_ref[l][\\'name\\']})\" for l in res[\"crit_path\"])\n",
    "        st.markdown(f\\'\\'\\'<div class=\"card\"><div class=\"section-label\">Critical Path</div>\n",
    "          <div style=\"font-size:1.15rem;color:#dc2626;line-height:2.1;\">{path_str}</div></div>\\'\\'\\', unsafe_allow_html=True)\n",
    "\n",
    "        st.markdown(\\'<div class=\"section-label\">Duration Distribution</div>\\', unsafe_allow_html=True)\n",
    "        fig, ax = plt.subplots(figsize=(9, 4))\n",
    "        fig.patch.set_facecolor(\"#ffffff\")\n",
    "        ax.set_facecolor(\"#f8f9ff\")\n",
    "        n_bins = min(60, int(np.sqrt(len(durations))))\n",
    "        counts, bin_edges, patches = ax.hist(durations, bins=n_bins, color=\"#6366f1\", edgecolor=\"#ffffff\", linewidth=0.4, alpha=0.85)\n",
    "        for patch, left in zip(patches, bin_edges[:-1]):\n",
    "            if left >= sl_val:\n",
    "                patch.set_facecolor(\"#ef4444\"); patch.set_alpha(0.8)\n",
    "        ax.axvline(mean_dur, color=\"#4f46e5\", linewidth=2, linestyle=\"--\", label=f\"Mean: {mean_dur:.1f}\")\n",
    "        ax.axvline(sl_val,   color=\"#dc2626\", linewidth=2, linestyle=\":\",  label=f\"{sl}th pct: {sl_val:.1f}\")\n",
    "        ax.set_xlabel(f\"Project Duration ({unit})\", color=\"#555\", fontsize=14)\n",
    "        ax.set_ylabel(\"Frequency\", color=\"#555\", fontsize=14)\n",
    "        ax.tick_params(colors=\"#555\", labelsize=13)\n",
    "        for spine in ax.spines.values(): spine.set_edgecolor(\"#dde1f0\")\n",
    "        ax.legend(facecolor=\"#ffffff\", edgecolor=\"#dde1f0\", labelcolor=\"#333\", fontsize=13)\n",
    "        fig.tight_layout(pad=1.5)\n",
    "        st.pyplot(fig)\n",
    "        plt.close(fig)\n",
    "\n",
    "        st.markdown(\\'<div class=\"section-label\">PERT Activity Breakdown</div>\\', unsafe_allow_html=True)\n",
    "        breakdown = [{\"Label\": lbl, \"Activity\": info[\"name\"],\n",
    "                      f\"PERT Mean ({unit})\": round(pert_mean(info[\"min\"], info[\"avg\"], info[\"max\"]), 2),\n",
    "                      \"Std Dev\": round(pert_std(info[\"min\"], info[\"max\"]), 2),\n",
    "                      \"Critical\": \"YES\" if lbl in res[\"crit_path\"] else \"\"}\n",
    "                     for lbl, info in acts_ref.items()]\n",
    "        st.dataframe(pd.DataFrame(breakdown), use_container_width=True, hide_index=True)\n",
    "\n",
    "        st.markdown(f\\'\\'\\'<div class=\"card\" style=\"margin-top:1rem;\">\n",
    "          <div class=\"section-label\">Interpretation</div>\n",
    "          <p style=\"color:#333;font-size:1.15rem;line-height:1.9;margin:0\">\n",
    "            Based on <strong style=\"color:#4f46e5\">{n_sim:,}</strong> simulations, the project is expected to take\n",
    "            <strong style=\"color:#4f46e5\">{mean_dur:.1f} {unit.lower()}</strong> on average.\n",
    "            For a <strong style=\"color:#dc2626\">{sl}% service level</strong>, plan for\n",
    "            <strong style=\"color:#dc2626\">{sl_val:.1f} {unit.lower()}</strong>.\n",
    "            Critical path: <strong style=\"color:#dc2626\">{\" > \".join(res[\"crit_path\"])}</strong>.\n",
    "          </p></div>\\'\\'\\', unsafe_allow_html=True)\n",
    "\n",
    "        st.markdown(\"---\")\n",
    "        st.markdown(\\'<div class=\"section-label\">Export Results</div>\\', unsafe_allow_html=True)\n",
    "        try:\n",
    "            excel_data = export_to_excel(acts_ref, durations, res[\"pert_dur\"], res[\"crit_path\"], sl, unit)\n",
    "            st.download_button(\n",
    "                label=\"Download Excel Report\",\n",
    "                data=excel_data,\n",
    "                file_name=\"projectpert_results.xlsx\",\n",
    "                mime=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",\n",
    "                use_container_width=True,\n",
    "            )\n",
    "        except Exception as e:\n",
    "            st.error(f\"Export error: {e}\")\n",
    "\n",
    "    else:\n",
    "        st.markdown(\\'\\'\\'<div style=\"height:420px;display:flex;flex-direction:column;align-items:center;justify-content:center;\n",
    "            border:2px dashed #c7cce8;border-radius:14px;background:#ffffff;text-align:center;gap:1rem;\">\n",
    "          <div style=\"font-size:3.5rem;\">📊</div>\n",
    "          <div style=\"font-size:1.2rem;color:#999;\">Configure activities on the left<br>then click Run Simulation</div>\n",
    "        </div>\\'\\'\\', unsafe_allow_html=True)\n",
    "'''\n",
    "\n",
    "with open(\"/Users/minchen/Desktop/project_pert_app.py\", \"w\") as f:\n",
    "    f.write(code)\n",
    "print(\"✅ File saved!\")\n",
    "\n",
    "import subprocess\n",
    "subprocess.Popen([\"streamlit\", \"run\", \"/Users/minchen/Desktop/project_pert_app.py\"])\n",
    "print(\"🚀 Launching...\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d911279b-5456-4087-acad-4b6c25bd24b8",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (base)",
   "language": "python",
   "name": "base"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
